version: '3.8'
services:
  ewm-service:
    container_name: ewm-service
    build: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/postgres


  stats-server:
    container_name: stats-server
    build: ewm-stat-service
    ports:
      - "9090:9090"
    depends_on:
      - db2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2/postgres

  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db2:
    container_name: db2
    image: postgres:15-alpine
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres