version: '3.1'
services:
  stats:
    build: stat-service/server
    image: explore-with-me-server
    container_name: explore-with-me-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6540:5431"
    environment:
      - POSTGRES_DB=jdbc:h2:mem:statservice
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ewm-service
    image: explore-with-me-ewm-service
    container_name: explore-with-me-ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-service-db

  ewm-service-db:
    image: postgres:14-alpine
    container_name: ewm-service-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=jdbc:h2:mem:ewmmainservice
      - POSTGRES_USER=ewmservice
      - POSTGRES_PASSWORD=ewmservice